name: Deploy a stage (predeploy, deploy, postdeploy)

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  predeploy-stage:
    runs-on: ubuntu-latest
    name: Deploy predeploy resources
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions
        with:
          app: ${{ inputs.app }}
          env: ${{ inputs.env }}
  deploy-stage:
    runs-on: ubuntu-latest
    needs: [predeploy-stage]
    name: Deploy app resources
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions
        with:
          app: ${{ inputs.app }}
          env: ${{ inputs.env }}
  postdeploy-stage:
    runs-on: ubuntu-latest
    needs: [deploy-stage]
    name: Deploy postdeploy resources
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions
        with:
          app: ${{ inputs.app }}
          env: ${{ inputs.env }}
