name: x-demo-cloudrun-dev

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployments
        run: echo "do nothing"
      - name: Pre-deployment tasks
        run: echo "do nothing"
      - name: Kube auth
        run: echo "do nothing"
      - name: Pre-deployment k8s tasks
        run: echo "do nothing"
      - name: Pre-deployment Cloud Run Job tasks
        run: echo "do nothing"
      - name: Pre-deployment k8s tasks
        run: echo "do nothing"
      - name: Upload Config
        run: echo "do nothing"
      - name: Deploy Cloud Run
        run: echo "do nothing"
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Post-deployment tasks
        run: echo "do nothing"
      - name: Post-deployment Cloud Run Job tasks
        run: echo "do nothing"
      - name: Create Deploy Success Event
        run: echo "do nothing"
  Wrap-up:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up workspace
        run: echo "do nothing"
