name: x-demo-cloudrun-pipeline

on:
  push:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: koustubh25/test/.github/workflows/deploy.yaml@main
        with:
          MY_VARIABLE: ${{ env.MY_VARIABLE }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
