name: Build all

on:
  push:

jobs:
  list-apps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps: ["config/x-demo-cloudrun", "config/x-demo-cloudrun-bg"]
    steps:
      - run: echo "app=${{ matrix.apps }}" >> "GITHUB_OUTPUT"
        id: appname
    outputs:
      app: ${{ steps.appname.outputs.app }}

  build-all:
    needs: [list-apps]
    max-par
    strategy:
      matrix:
        environments: ["dev", "np"]
    uses: koustubh25/test/.github/workflows/deploy.yaml@main
    with:
      environment: ${{ matrix.environments }}
      MY_VARIABLE: ${{ needs.list-apps.outputs.app }}
