# app : ["app1", "app2"] in parallel
# stages/envs: [["dev"], ["sit1, sit2"]]

name: Build-all

on:
  workflow_call:

jobs:
  discover-apps:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - run: |
          pwd
          cd ${{ github.event.repository.name }}
          ls

  build-apps:
    needs: [discover-apps]
    strategy:
      max-parallel: 1
      matrix:
        envs: [["dev"]]
    uses: ./.github/workflows/workflow-app.yaml
    with:
      apps: '["config/x-demo-cloudrun", "config/x-demo-cloudrun-bg"]'
      envs: ${{ toJSON(matrix.envs) }}
