# app : ["app1", "app2"] in parallel
# stages/envs: [["dev"], ["sit1, sit2"]]

name: Build-all

on:
  workflow_call:

jobs:
  discover-apps:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.getapps.outputs.apps}}
    defaults:
      run:
        working-directory: ${{ github.event.repository.name }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.34.2
      - id: getapps
        run: |
          apps=($(grep -l "apps.x.anz.com" **/*.yaml | xargs -I{} dirname {}))
          echo "apps=$(jq -c -n '$ARGS.positional' --args ${apps[@]})" >> "$GITHUB_OUTPUT"

  build-apps:
    needs: [discover-apps]
    strategy:
      max-parallel: 1
      matrix:
        envs: [["dev"]]
    uses: ./.github/workflows/workflow-app.yaml
    with:
      apps: ${{ needs.discover-apps.outputs.apps }}
      envs: ${{ toJSON(matrix.envs) }}
