name: Build-all

on:
  workflow_call:

jobs:
  discover-apps:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.discoverapps.outputs.apps}}
      envs: ${{ steps.getenvs.outputs.envs }}
    defaults:
      run:
        working-directory: ${{ github.event.repository.name }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      # Is the below necessary or can be retrieved from `x inventory list` and matching the repo name and base fields?
      # Probably can't use it as these will contain new apps
      - id: discoverapps
        name: Discover apps
        run: |
          # Identify x apps from xCRD
          apps=($(grep -rl --exclude-dir="\.github"  "apps.x.anz.com" . | xargs -I{} dirname {}))
          echo "apps=$(jq -c -n '$ARGS.positional' --args ${apps[@]})" >> "$GITHUB_OUTPUT"
      - id: getenvs
        name: Get Environments
        run: |
          # This command doesn't exist, but something like this is needed which provides enviornments in order
          echo "Running 'x workspace environments list --order (--vs x)'"
          echo "envs=[[\"dev\"],[\"sit1\",\"sit2\",\"sit3\"],[\"prod\"]]" >> "$GITHUB_OUTPUT"

  build-apps:
    needs: [discover-apps]
    strategy:
      max-parallel: 1
      matrix:
        envs: ${{ fromJSON(needs.discover-apps.outputs.envs) }} # 1 set of environments
        stages: ["predeploy", "deploy", "postdeploy"]
    uses: ./.github/workflows/workflow-app.yaml
    with:
      apps: ${{ needs.discover-apps.outputs.apps }}
      envs: ${{ toJSON(matrix.envs) }}
      stage: ${{ matrix.stages }}
