# app : ["app1", "app2"] in parallel
# stages/envs: [["dev"], ["sit1, sit2"]]

name: Build-all

on:
  workflow_call:

jobs:
  discover-apps:
    run: |
      echo "checking if already checked out"
      pwd
      ls

  build-apps:
    strategy:
      max-parallel: 1
      matrix:
        envs: [["dev"], ["sit5", "sit2", "sit3"], ["prod"]]
    uses: ./.github/workflows/workflow-app.yaml
    with:
      apps: '["config/x-demo-cloudrun", "config/x-demo-cloudrun-bg"]'
      envs: ${{ toJSON(matrix.envs) }}
