# app : ["app1", "app2"] in parallel
# stages/envs: [["dev"], ["sit1, sit2"]]

name: Build-all

on:
  push:

jobs:
  build-apps:
    strategy:
      max-parallel: 1
      matrix:
        envs: [["dev"], ["sit1", "sit2", "sit3"], ["prod"]]
    uses: ./.github/workflows/workflow-app.yaml
    with:
      app: ${{ toJSON(["config/x-demo-cloudrun", "config/x-demo-cloudrun-bg"]) }}
      envs: ${{ toJSON(matrix.envs) }}
