name: Test workflow

on:
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job1"
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job2"
