name: workflow-app

on:
  workflow_call:
    inputs:
      apps:
        required: true
        type: string
      envs:
        required: true
        type: string

jobs:
  deploy-app-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envs) }}
        app: ${{ fromJSON(inputs.apps) }}
    environment: ${{ matrix.env }}
    steps:
      - run: |
          echo ${{ matrix.env }}
          echo ${{ inputs.app }}
          sleep 10
