name: workflow-stage

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        stages: ["predeploy", "deploy", "postdeploy"]
    environment: ${{ inputs.env }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: Merge into x-deployments
        run: |
          echo "docker run x-github-actions:rapid generate.manifests.env"
          # internally uses x manifest gen --base=${{ matrix.app }} --filter env=${{ matrix.env }}'
          # This creates PR and merges into x-deployments
          echo ${{ matrix.app }}
          echo ${{ matrix.env }}
          sleep 10
