name: workflow-app

on:
  workflow_call:
    inputs:
      apps:
        required: true
        type: string
      envs:
        required: true
        type: string

jobs:
  deploy-app-env:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.repository.name }}
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envs) }}
        app: ${{ fromJSON(inputs.apps) }}
    environment: ${{ matrix.env }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - run: |
          echo ${{ matrix.env }}
          echo ${{ matrix.app }}
          sleep 10
