name: workflow-app

on:
  workflow_call:
    inputs:
      apps:
        required: true
        type: string
      envs:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  deploy-app-env:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.repository.name }}
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envs) }}
        app: ${{ fromJSON(inputs.apps) }}
    environment: ${{ matrix.env }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
      - name: Merge into x-deployments
        run: |
          echo "docker run x-github-actions:rapid generate.manifests.env"
          # internally uses x manifest gen --base=${{ matrix.app }} --filter env=${{ matrix.env }}'
          # This creates PR and merges into x-deployments
          echo ${{ inputs.stage }}
          sleep 10
