name: workflow-app

on:
  workflow_call:
    inputs:
      apps:
        required: true
        type: string
      envs:
        required: true
        type: string

jobs:
  deploy-app-env:
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envs) }}
        app: ${{ fromJSON(inputs.apps) }}
    environment: ${{ matrix.env }}
    uses: ./.github/workflows/workflow-stage.yaml
    with:
      app: ${{ matrix.app }}
      env: ${{ matrix.env }}
