name: workflow-app

on:
  workflow_call:
    inputs:
      apps:
        required: true
        type: string
      envs:
        required: true
        type: string

jobs:
  deploy-app-env:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.repository.name }}
    strategy:
      matrix:
        env: ${{ fromJSON(inputs.envs) }}
        app: ${{ fromJSON(inputs.apps) }}
    environment: ${{ matrix.env }}
    steps:
      - uses: ./.github/workflows/workflow-stage.yaml
        with:
          app: ${{ matrix.app }}
          env: ${{ matrix.env }}
