name: workflow-app

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      envs:
        required: true
        type: string

jobs:
  deploy-app-env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs: ${{ fromJSON(inputs.envs) }}
    run: |
      echo ${{ matrix.envs }}
